# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'all.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 667)
        self.main_layout = QtWidgets.QWidget(MainWindow)
        self.main_layout.setObjectName("main_layout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_layout)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.main_layout)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.today_groups = QtWidgets.QTableWidget()
        self.today_groups.setColumnCount(2)
        self.today_groups.setHorizontalHeaderLabels(['Группы', 'Время'])
        self.today_groups.setObjectName("today_groups")

        self.horizontalLayout.addWidget(self.today_groups)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendar = QtWidgets.QCalendarWidget(self.main_layout)
        self.calendar.setObjectName("calendar")
        self.verticalLayout.addWidget(self.calendar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.main_layout)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.teacher_menu = QtWidgets.QMenu(self.menubar)
        self.teacher_menu.setObjectName("teacher_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.add_group = QtWidgets.QAction(MainWindow)
        self.add_group.setObjectName("add_group")
        self.config_groups = QtWidgets.QAction(MainWindow)
        self.config_groups.setObjectName("config_groups")
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.menu.addAction(self.add_group)
        self.menu.addAction(self.config_groups)
        self.menu.addSeparator()
        self.menu.addAction(self.exit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.teacher_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Расписание на сегодняшний день"))
        self.menu.setTitle(_translate("MainWindow", "Группы"))
        self.teacher_menu.setTitle(_translate("MainWindow", "Преподаватель"))
        self.add_group.setText(_translate("MainWindow", "Добавить группу"))
        self.config_groups.setText(_translate("MainWindow", "Редактировать группы"))
        self.exit.setText(_translate("MainWindow", "Выход из учетной записи"))
